### PR TITLE
TracyHandler: delete local file after upload

### PR DESCRIPTION
**Pull request by VojtaStanek**
I have encountered a problem that log directory used all the space on the machine. It doesn't make sense for me to store files locally if the file is uploaded. I have added an option (`$removeUploads`) to preserve current behavior, but the default is to delete local file.

### CODE REVIEW

**Comment by JanTvrdik** [comment]
The reason the files are kept locally is to prevent duplicate bluescreens from being uploaded (`renderToFile` returns `false` in that case). This is important functionality, so we cannot default to deleting them. Truncating them on the other hand should be fine. Or some smart GC would need to be used to delete bluescreens older than some age.

**Comment by VojtaStanek** [comment]
Makes sense. I have changed it so that: 
- The file contents is replaced with a small string.
- After few days files are deleted.

**Comment by JanTvrdik** [comment]
Thank you. I fixed few minor issues (clock usage, consistent UTC usage, `!` to force reset time to `00:00`, ...) and merged it.

**Comment by VojtaStanek** [comment]
Thanks Honzo for polishing and release!

**Pull request merged**
